#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Script to prepare packages for publishing by creating publishable package.json files in dist folders
 */

const packages = [
  {
    name: 'qortex-query',
    path: 'packages/query',
    publishName: 'qortex-query',
    description: 'Framework-agnostic query cache & fetch registry (MFE friendly).',
    persisterExport: 'persister'
  },
  {
    name: 'qortex-query-react',
    path: 'packages/query-react',
    publishName: 'qortex-query-react',
    description: 'React hook bridge for qortex runtime',
    persisterExport: 'persister',
    // Transform workspace dependencies to published versions
    dependencyTransforms: {
      'qortex-query': 'qortex-query' // workspace:* -> qortex-query (same version)
    }
  },
  {
    name: 'qortex-db',
    path: 'packages/db',
    publishName: 'qortex-db',
    description: 'Browser-only Redis-like key-value database with localStorage, sessionStorage, and IndexedDB support',
    subExports: ['query', 'store']
  },
  {
    name: 'qortex-store',
    path: 'packages/store',
    publishName: 'qortex-store',
    description: 'Framework-agnostic lightweight state management library'
  },
  {
    name: 'qortex-store-react',
    path: 'packages/store-react',
    publishName: 'qortex-store-react',
    description: 'React bindings for qortex-store state management',
    dependencyTransforms: {
      'qortex-store': 'qortex-store' // workspace:* -> qortex-store (same version)
    }
  },
  {
    name: 'qortex-resource',
    path: 'packages/resource',
    publishName: 'qortex-resource',
    description: 'End-to-End Data Lifecycle Management for the qortex ecosystem',
    subExports: ['query', 'validate', 'optimistic', 'persist'],
    dependencyTransforms: {
      'qortex-query': 'qortex-query'
    }
  },
  {
    name: 'qortex-resource-react',
    path: 'packages/resource-react',
    publishName: 'qortex-resource-react',
    description: 'React bindings for qortex-resource',
    dependencyTransforms: {
      'qortex-resource': 'qortex-resource'
    }
  }
];

function createPublishablePackageJson(pkg) {
  const srcPackageJsonPath = path.join(pkg.path, 'package.json');
  const distPackageJsonPath = path.join(pkg.path, 'dist', 'package.json');
  const distPath = path.join(pkg.path, 'dist');

  // Read the source package.json
  const srcPackageJson = JSON.parse(fs.readFileSync(srcPackageJsonPath, 'utf8'));

  // Ensure dist folder exists before proceeding
  if (!fs.existsSync(distPath)) {
    console.log(`⏳ Skipping ${pkg.name}: dist folder not found yet.`);
    return;
  }

  // Transform dependencies if needed
  let dependencies = { ...(srcPackageJson.dependencies || {}) };
  if (pkg.dependencyTransforms) {
    Object.entries(pkg.dependencyTransforms).forEach(([workspaceDep, publishedDep]) => {
      if (dependencies[workspaceDep]) {
        // Replace workspace dependency with published version
        if (workspaceDep !== publishedDep) {
          dependencies[publishedDep] = srcPackageJson.version; // Use same version
          delete dependencies[workspaceDep];
        } else {
          // Same name, just replace the value
          dependencies[publishedDep] = srcPackageJson.version;
        }
      }
    });
  }

  // Build exports and files arrays dynamically based on what's in dist folder
  const exports = {
    ".": {
      "types": "./index.d.ts",
      "import": "./index.mjs",
      "require": "./index.js"
    }
  };

  const files = [
    "index.js",
    "index.mjs",
    "index.d.ts"
  ];

  // Helper to add sub-exports
  const addExport = (exportName) => {
    const exportFiles = [
      `${exportName}.js`,
      `${exportName}.mjs`,
      `${exportName}.d.ts`
    ];

    // Check if all export files exist
    const allExist = exportFiles.every(file =>
      fs.existsSync(path.join(distPath, file))
    );

    if (allExist) {
      exports[`./${exportName}`] = {
        "types": `./${exportName}.d.ts`,
        "import": `./${exportName}.mjs`,
        "require": `./${exportName}.js`
      };

      files.push(...exportFiles);
    }
  };

  // Add individual sub-exports if defined
  if (pkg.subExports) {
    pkg.subExports.forEach(addExport);
  }

  // Add persister export if defined (legacy support)
  if (pkg.persisterExport) {
    addExport(pkg.persisterExport);
  }

  // Add shared types files (generated by tsup for internal types)
  const distFiles = fs.readdirSync(distPath);
  const sharedTypesFiles = distFiles.filter(file =>
    file.startsWith('types-') && file.endsWith('.d.ts')
  );

  if (sharedTypesFiles.length > 0) {
    files.push(...sharedTypesFiles);
    console.log(`📁 Added shared types files: ${sharedTypesFiles.join(', ')}`);
  }

  files.push("README.md");

  // Create publishable package.json
  const publishablePackageJson = {
    name: pkg.publishName,
    version: srcPackageJson.version,
    description: pkg.description,
    main: "index.js",
    module: "index.mjs",
    types: "index.d.ts",
    sideEffects: srcPackageJson.sideEffects || false,
    exports: exports,
    publishConfig: {
      "access": "public"
    },
    files: files,
    repository: srcPackageJson.repository,
    homepage: srcPackageJson.homepage,
    bugs: srcPackageJson.bugs,
    keywords: srcPackageJson.keywords,
    author: srcPackageJson.author,
    license: srcPackageJson.license,
    // Include transformed dependencies but not devDependencies
    dependencies: dependencies,
    peerDependencies: srcPackageJson.peerDependencies || {}
  };

  // Create publishable package.json in dist
  fs.writeFileSync(distPackageJsonPath, JSON.stringify(publishablePackageJson, null, 2));

  // ─── NEW: Create proxy folders in SOURCE ROOT for local/monorepo resolution ───
  if (pkg.subExports) {
    pkg.subExports.forEach(exportName => {
      const proxyPath = path.join(pkg.path, exportName);
      const proxyPkgJsonPath = path.join(proxyPath, 'package.json');

      if (!fs.existsSync(proxyPath)) {
        fs.mkdirSync(proxyPath, { recursive: true });
      }

      const proxyPkgJson = {
        name: `${pkg.publishName}/${exportName}`,
        main: `../dist/${exportName}.js`,
        module: `../dist/${exportName}.mjs`,
        types: `../dist/${exportName}.d.ts`
      };

      fs.writeFileSync(proxyPkgJsonPath, JSON.stringify(proxyPkgJson, null, 2));
      console.log(`🔗 Created local proxy for ${pkg.name}/${exportName}`);
    });
  }

  // Copy README.md to dist folder
  const srcReadmePath = path.join(pkg.path, 'README.md');
  const distReadmePath = path.join(pkg.path, 'dist', 'README.md');

  if (fs.existsSync(srcReadmePath)) {
    fs.copyFileSync(srcReadmePath, distReadmePath);
    console.log(`✅ Copied README.md for ${pkg.name}`);
  } else {
    console.log(`⚠️  No README.md found for ${pkg.name}`);
  }

  console.log(`✅ Created publishable package.json for ${pkg.name}`);
}

// Create publishable package.json for each package
packages.forEach(createPublishablePackageJson);

console.log('🎉 All publishable package.json files created successfully!');
